<?php
$menus = [['kesenian', 'kesenian'],['migrations', 'migrations'],['parade', 'parade'],['pbb', 'pbb'],['peserta', 'peserta'],['samapta', 'samapta'],['users', 'users'],['wawancara', 'wawancara'],
];
?>
<ul class="nav flex-column">
    <?php foreach ($menus as $m) : ?>
        <li class="nav-item">
            <a class="nav-link" href="<?= base_url() . '/' . $m[0] ?>"> <?= $m[1] ?></a>
        </li>
    <?php endforeach; ?>
</ul>



<?php 
/* End of file views/layout/sidebar.php */
/* Location: ./app/views/layout */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-06-05 10:18:16 */
?>